### ISSUE TITLE
can you integrate Tencent map

### ISSUE THREAD

**Issue by huangred** [mattermoran/map_launcher#50]
integrate Tencent map

**Comment by xalanq** [comment]
FYI: https://lbs.qq.com/webApi/uriV1/uriGuide/uriMobileGuide

**Comment by mattermoran** [comment]
@xalanq thanks! I added based on docs but I can't test as I don't have api key. Could you guys check and let me if it works?
You can install version from a branch feature/tencent by changing to this in pubspec.yaml file:
```yaml
map_launcher:
    git:
      url: https://github.com/mattermoran/map_launcher
      ref: feature/tencent
```
