### ISSUE TITLE
map_launcher 1.0.0 fails to build on Flutter 1.22.4 with several error messages

### ISSUE THREAD

**Issue by insinfo** [mattermoran/map_launcher#53]
map_launcher 1.0.0 fails to build on Flutter 1.22.4 with several error messages

```console
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-0.4.5\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (14, 20): Redeclaration: MapType
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-0.4.5\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (16, 15): Redeclaration: MapModel
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-0.4.5\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (22, 7): Redeclaration: MapLauncherPlugin
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (14, 20): Redeclaration: MapType
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (16, 15): Redeclaration: MapModel
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (16, 37): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (18, 43): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (22, 7): Redeclaration: MapLauncherPlugin
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (35, 55): No value passed for parameter 'context'
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (35, 55): No value passed for parameter 'activity'
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (35, 55): No value passed for parameter 'pm'
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (36, 31): Unresolved reference: channel
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (37, 13): Val cannot be reassigned
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (37, 31): Cannot access 'context': it is private in 'MapLauncherPlugin'
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (38, 31): Unresolved reference: channel
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (43, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (43, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (43, 30): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (44, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (44, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (44, 30): Unresolved reference: googleGo
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (45, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (45, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (45, 30): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (46, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (46, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (46, 30): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (47, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (47, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (47, 30): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (48, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (48, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (48, 30): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (49, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (49, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (49, 30): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (50, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (50, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (50, 30): Unresolved reference: citymapper
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (51, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (51, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (51, 30): Unresolved reference: mapswithme
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (52, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (52, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (52, 30): Unresolved reference: osmand
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (53, 13): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (53, 22): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (53, 30): Unresolved reference: doubleGis
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (56, 42): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (58, 87): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (64, 47): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (64, 55): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (77, 36): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (81, 47): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (81, 51): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (81, 59): No method 'equals(Any?): Boolean' available
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (82, 17): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (82, 26): No method 'equals(Any?): Boolean' available
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (83, 44): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (95, 63): Cannot access 'MapModel': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (105, 31): Cannot access 'MapType': it is private in file
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\map_launcher-1.0.0\android\src\main\kotlin\com\alexmiller\map_launcher\MapLauncherPlugin.kt: (105, 39): Cannot access 'MapType': it is private in file

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':map_launcher:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        68,3s
Exception: Gradle task assembleDebug failed with exit code 1
```

pubspec.yaml
```yaml

name: riodasostrasapp
description: App Oficial da Prefeitura de Rio das Ostras
version: 1.0.2+3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  connectivity: ^2.0.2
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  map_launcher: ^1.0.0
  device_id: ^0.2.0
  device_info: ^1.0.0
  location_permissions: ^3.0.0+1
  location: ^3.1.0
  flutter_inappwebview: ^4.0.0+4

  #firebase services
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.16

  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  flutter_advanced_networkimage: ^0.7.0
 
  #webview_flutter: ^0.3.22+1
  webview_flutter: ^1.0.7
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  queries: ^0.1.14
  #flutter_svg: ^0.17.4
  intl: ^0.16.1

  http: ^0.12.2
  dio: ^3.0.10
  universal_html: ^1.2.2
  essential_rest: ^1.1.22
  #wideget para infinit scroll
  incrementally_loading_listview: ^0.3.0
  
  #bloc state manager  
  flutter_bloc: ^4.0.0 #^3.2.0
  bloc: ^4.0.0
  #mobx state manager
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  #redux state manager
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  redux_thunk: ^0.3.0
  #provider state manager
  provider: ^4.1.2
  flutter_modular: ^2.0.1
  equatable: ^1.1.1

  carousel_slider: ^2.3.1
  #para armazenar o token  
  flutter_secure_storage: ^3.3.5
  #gerar codigo qr
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  jaguar_jwt: ^2.1.6

  riodasostrasapp_core:
    hosted:
      name: riodasostrasapp_core
      url: http://pub.riodasostras.rj.gov.br:4000
    version: ^1.0.39

dependency_overrides:
  rxdart: ^0.24.1
  #flutter_svg: ^0.19.2+1
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2
  slidy: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700      
    - family: pmro_app
      fonts:
        - asset: assets/fonts/pmro.ttf         
     
   
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
      
```
